media:
  input: public/uploads
  output: /uploads
  categories: [image]

content:
  - name: home
    label: Home Page
    type: file
    path: content/homepage.json
    format: json
    fields:
      - name: eyebrow
        label: Eyebrow
        type: string
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: image
        label: Feature Image
        type: image
      - name: imageAlt
        label: Image Alt Text
        type: string
        required: true
